site_name: 'facileManager Documentation'
site_url: 'https://docs.facilemanager.com/'
repo_url: 'https://github.com/facileManager/facileManager-docs'
copyright:
validation:
  links:
    anchors: warn
theme: 
  name: material
  #name: readthedocs
  logo: images/fm.png

nav:
  - 'Overview': index.md
  - 'Getting Started':
    - 'Prerequisites': main/prerequisites.md
    - 'Installation': main/basic-install.md
    - 'Post-Install': main/post-install.md
    - 'Updating': main/update.md
  - 'Administration':
    - 'Settings': main/settings.md
    - 'Users & Groups': main/user-management.md
    - 'config.inc.php': main/config.inc.php.md
  - 'Modules':
    - 'Getting Started': modules/index.md
    - 'fmDHCP':
      - 'Getting Started' : 
        - 'Server Interaction' : modules/fmDHCP/getting-started/servers.md
      - 'Settings' : modules/fmDHCP/settings.md
      - 'client.php' : modules/fmDHCP/client.php.md
    - 'fmDNS':
      - 'Getting Started' : 
        - 'Server Interaction' : modules/fmDNS/getting-started/servers.md
        - 'Zones' : modules/fmDNS/getting-started/zones.md
        - 'Records' : modules/fmDNS/getting-started/records.md
      - 'Settings' : modules/fmDNS/settings.md
      - 'client.php' : modules/fmDNS/client.php.md
      - 'Examples' : 
        - 'Split-View' : modules/fmDNS/examples/split-view.md
    - 'fmFirewall':
      - 'Getting Started' : 
        - 'Server Interaction' : modules/fmFirewall/getting-started/servers.md
      - 'client.php' : modules/fmFirewall/client.php.md
    - 'fmSQLPass':
      - 'Getting Started' : modules/fmSQLPass/index.md
      - 'Settings' : modules/fmSQLPass/settings.md
    - 'fmWifi':
      - 'Getting Started' : 
        - 'Server Interaction' : modules/fmWifi/getting-started/servers.md
      - 'Settings' : modules/fmWifi/settings.md
      - 'client.php' : modules/fmWifi/client.php.md
  - 'fM API':
    - 'REST API': api/index.md
    - 'Authentication': api/auth.md
    - 'Return Codes': api/codes.md
    - 'client.php' : api/client.php.md
  # - 'FAQ': main/faq.md

markdown_extensions:
  # Code highlighting in ``` ``` blocks, superseeds codehilite
  - pymdownx.highlight
  # allows for the nesting of code blocks inside other blocks
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # Table of Contents
  # https://python-markdown.github.io/extensions/toc/
  - toc:
      permalink: true
  # block-styled side content
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
  - pymdownx.details

  # Format tables
  - tables

  # linkifies URL and email links without having to wrap them in Markdown syntax. Also, allows shortens repository issue, pull request, and commit links.
  # - pymdownx.magiclink
  # Task lists (https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/)
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # Highlight words with ==mark me==
  # - pymdownx.mark
  # Adds support for deletion ~~Delete me~~ and subscript text~a\ subscript~
  # - pymdownx.tilde
  # This extension is a convenience extension which includes many pymdownx extensions
  # (https://facelessuser.github.io/pymdown-extensions/extensions/extra/)
  # - pymdownx.extra

  # Tabbed provides a syntax to easily add tabbed Markdown content.
  # https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.tabbed:
      alternate_style: true
  # Adds syntax for defining footnotes in Markdown documents (https://squidfunk.github.io/mkdocs-material/reference/footnotes/)
  # - footnotes
  # Adds the ability to define abbreviations (https://squidfunk.github.io/mkdocs-material/reference/tooltips/)
  # - abbr
  # - attr_list
  # Include files in other documents like {!some/dir/in/docs/filename.md!}
  # - markdown_include.include:
  #     base_path: docs
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/modules/common/
  #     # auto_append abbreviations.md to every file
  #     # https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary
  #     auto_append:
  #       - docs/abbreviations.md
  # Include files in other documents like {!some/dir/in/docs/filename.md!}
  # - markdown_include.include:
  #     base_path: docs
  # Metadata support in pages
  # (https://squidfunk.github.io/mkdocs-material/extensions/metadata/)
  # - meta
  # Tabbed provides a syntax to easily add tabbed Markdown content.
  # (https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)
  # - pymdownx.tabbed
  # InlineHilite is an inline code highlighter inspired by CodeHilite.
  # (https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/)
  # - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - extra.css

plugins:
  - search
  # - git-revision-date-localized:
  #     fallback_to_build_date: true
