name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
